name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags para las pruebas'
        required: false
        default: ''
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 24
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Cucumber tests
      run: |
        if [ -z "${{ github.event.inputs.tags }}" ]; then
          npm test
        else
          npm test -- --tags "${{ github.event.inputs.tags }}"
        fi
    - name: Generate Serenity Report
      if: ${{ !cancelled() }}
      run: npm run report
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: serenity-report
        path: target/site/serenity/
        retention-days: 30
