name: Playwright Tests
on:
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Selecciona el navegador (dejar vacío para ejecutar en todos)'
        required: false
        default: 'todos'
        type: choice
        options:
          - todos
          - chromium
          - firefox
      tags:
        description: 'Tags para las pruebas (ej: @test, @smoke)'
        required: false
        default: ''
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Cucumber tests
      run: |
        ARGS=""
        if [ ! -z "${{ github.event.inputs.tags }}" ]; then
          ARGS="$ARGS --grep ${{ github.event.inputs.tags }}"
        fi
        if [ "${{ github.event.inputs.browser }}" != "todos" ] && [ ! -z "${{ github.event.inputs.browser }}" ]; then
          ARGS="$ARGS --project ${{ github.event.inputs.browser }}"
        fi
        npm test -- $ARGS
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
